#' Plot a simulated epidemic
#'
#' @name plot.sim_epi
#'
#' @description
#' Plot method for objects of class \code{"sim_epi"} as returned by
#' \code{\link{simulate_epi}}. The function can display either the compartmental
#' state trajectories (S, I, R) or the observed incidence time series, depending
#' on the value of the \code{what} argument.
#'
#' @details
#' When \code{what = "states"}, the function plots the time evolution of the
#' susceptible (S), infectious (I), and recovered (R) compartments on the same
#' figure. When \code{what = "incidence"}, the function plots the observed
#' incidence counts generated by the observation model.
#'
#' This method is automatically dispatched when calling \code{plot()} on an
#' object of class \code{"sim_epi"}.
#'
#' @param x Object of class \code{"sim_epi"} as returned by
#'   \code{\link{simulate_epi}}.
#' @param what Character. Type of plot to produce. Either \code{"states"} for the
#'   compartmental trajectories (S, I, R) or \code{"incidence"} for the observed
#'   incidence time series.
#' @param ... Additional graphical parameters passed to base plotting functions
#'   such as \code{\link{plot}} and \code{\link{lines}}.
#'
#' @return Invisibly returns the input object \code{x}.
#'
#' @seealso
#' \code{\link{simulate_epi}}, \code{\link{summary.epi_sim}}
#'
#' @examples
#' sim <- simulate_epi(n_days = 200, model = "sir", seed = 1)
#'
#' # Plot S, I, R trajectories
#' plot(sim)
#'
#' # Plot observed incidence
#' plot(sim, what = "incidence")
#'
#' @export
plot.sim_epi <- function(x, what = c("states", "incidence"), ...) {
  what <- match.arg(what)

  if (!is.list(x) || is.null(x$states)) {
    stop("Invalid 'sim_epi' object: missing $states.")
  }

  if (what == "states") {
    st <- x$states

    ymax <- max(st$S, st$I, st$R, na.rm = TRUE)

    plot(st$time, st$S,
         type = "l", lwd = 2,
         xlab = "Time (days)",
         ylab = "Number of individuals",
         main = paste("Simulation:", x$params$model),
         ylim = c(0, ymax),
         ...)

    lines(st$time, st$I, col = "red",  lwd = 2, lty = 2)
    lines(st$time, st$R, col = "blue", lwd = 2, lty = 3)

    legend("right",
           legend = c("Susceptible (S)", "Infectious (I)", "Recovered (R)"),
           col    = c("black", "red", "blue"),
           lty    = c(1, 2, 3),
           lwd    = 2,
           bty    = "n")

  } else {
    inc <- x$incidence_obs
    if (is.null(inc) || is.null(inc$time) || is.null(inc$inc)) {
      stop("Invalid 'sim_epi' object: missing $incidence_obs with columns time/inc.")
    }

    plot(inc$time, inc$inc,
         type = "h",
         xlab = "Time (days)",
         ylab = "Observed incidence",
         main = paste("Observed incidence:", x$params$model),
         ...)
  }

  invisible(x)
}



#' Summarize a simulated epidemic
#'
#' @name summary.epi_sim
#'
#' @description
#' Summary method for objects of class \code{"sim_epi"} as returned by
#' \code{\link{simulate_epi}}. The function computes and returns a small set of
#' epidemiologically meaningful summary quantities derived from the simulation.
#'
#' @details
#' The summary includes:
#' \describe{
#'   \item{model}{The epidemic model simulated (e.g. \code{"sir"} or \code{"sirs"}).}
#'   \item{R0}{The basic reproduction number, computed as
#'     \eqn{R_0 = \beta / \gamma}.}
#'   \item{peak_I}{The maximum number of infectious individuals observed during
#'     the simulation.}
#'   \item{total_infections}{The total number of infection events, computed as
#'     the maximum value of the cumulative infection variable \code{C(t)}.}
#' }
#'
#' This method is automatically dispatched when calling \code{summary()} on an
#' object of class \code{"sim_epi"}.
#'
#' @param object Object of class \code{"sim_epi"} as returned by
#'   \code{\link{simulate_epi}}.
#' @param ... Currently unused; included for compatibility with generic
#'   \code{\link{summary}}.
#'
#' @return
#' A named list with summary statistics describing the simulated epidemic.
#'
#' @seealso
#' \code{\link{simulate_epi}}, \code{\link{plot.sim_epi}}
#'
#' @examples
#' sim <- simulate_epi(n_days = 300, model = "sirs", omega = 1/180, seed = 1)
#'
#' summary(sim)
#'
#' @export
summary.epi_sim <- function(object, ...) {
  with(object, {
    list(
      model = params$model,
      R0 = params$beta / params$gamma,
      peak_I = max(states$I),
      total_infections = max(states$C)
    )
  })
}


#' Print a simulated epidemic
#'
#' @name print.sim_epi
#'
#' @description
#' Print method for objects of class \code{"sim_epi"} as returned by
#' \code{\link{simulate_epi}}. The function provides a concise, human-readable
#' summary of the simulated epidemic, including the model type, time horizon,
#' key parameters, and basic outcome metrics.
#'
#' @details
#' This method is automatically called when an object of class \code{"sim_epi"}
#' is printed. It is intended to give a quick overview without displaying the
#' full internal structure of the object.
#'
#' @param x Object of class \code{"sim_epi"} as returned by
#'   \code{\link{simulate_epi}}.
#' @param ... Currently unused; included for compatibility with generic dispatch.
#'
#' @return
#' Invisibly returns the input object \code{x}.
#'
#' @seealso
#' \code{\link{simulate_epi}}, \code{\link{summary.sim_epi}}, \code{\link{plot.sim_epi}}
#'
#' @examples
#' sim <- simulate_epi(n_days = 200, model = "sirs",
#'                     beta = 0.30, gamma = 0.10, omega = 1/180)
#'
#' sim
#'
#' @export
print.sim_epi <- function(x, ...) {

  if (!inherits(x, "sim_epi")) {
    stop("Object must be of class 'sim_epi'.")
  }

  p  <- x$params
  st <- x$states

  cat("Epidemic simulation\n")
  cat("-------------------\n")

  cat("Model:            ", toupper(p$model), "\n", sep = "")
  cat("Time horizon:     ", max(st$time), " days\n", sep = "")
  cat("Population (N):   ", format(p$N, scientific = TRUE), "\n", sep = "")

  cat("\nParameters\n")
  cat("  beta  (transmission): ", signif(p$beta, 4), "\n", sep = "")
  cat("  gamma (recovery):     ", signif(p$gamma, 4), "\n", sep = "")

  if (!is.null(p$omega) && p$model == "sirs") {
    cat("  omega (immunity loss):", signif(p$omega, 4),
        " (mean duration = ", signif(1 / p$omega, 4), " days)\n", sep = "")
  }

  cat("\nOutcomes\n")

  peak_I  <- max(st$I, na.rm = TRUE)
  time_pk <- st$time[which.max(st$I)]
  total_C <- max(st$C, na.rm = TRUE)

  cat("  Peak infectious:      ", format(round(peak_I), big.mark = ","), "\n", sep = "")
  cat("  Time of peak:         ", time_pk, " days\n", sep = "")
  cat("  Total infections (C): ", format(round(total_C), big.mark = ","), "\n", sep = "")

  invisible(x)
}
